[package]
name = "bevy_project1"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
rand = "0.8.5"
physical_constants = "0.5.0"
bevy_2d_line = "0.1.3"

[profile.dev.package."*"]
opt-level = 1